### ISSUE TITLE
St.Table is depreciated

### ISSUE THREAD

**Issue by bcomnes** [vibou/vibou.gTile#35]
I tired to get this to run on Gnome 3.18.1 by updating the metadata and quickly ran into bugs getting this to launch.  From `lg`:

```
St.Table is not a constructor
```

Looks like maybe the layout used is depreciated?  

https://github.com/projecthamster/shell-extension/issues/96

This thread seems to have some more details,  but still, fixing it looks like it might require porting to a new layout API.

**Comment by Talv** [comment]
There's already a working fork of gTile for gnome 3.18 that uses Clutter.TableLayout
https://github.com/lundal/vibou.gTile

**Comment by bcomnes** [comment]
Right on! Thanks for pointing that out @Talv :)   

@vibou do you want me to close this?  Any interest in consolidating repos?
