### ISSUE TITLE
Tiling sometimes applied to a part of the screen (e.g. upper half)

### ISSUE THREAD

**Issue by j0hannes** [vibou/vibou.gTile#39]
I haven't been able to figure out when this happens. Disabling and reenabling the extension helps.

**Comment by j0hannes** [comment]
before
![screenshot from 2016-03-19 11-02-55](https://cloud.githubusercontent.com/assets/3944397/13897926/9886086e-edc2-11e5-851d-ac88ecfa58d3.png)
and after restarting the extension
![screenshot from 2016-03-19 11-04-21](https://cloud.githubusercontent.com/assets/3944397/13897928/9b736076-edc2-11e5-859c-af24963dbf81.png)

**Comment by scherepanov** [comment]
Got email seems to be from you about guile scaling
Are keyboard presets working? Try super-alt-(1,2,3,4). This is pre-configured 4 corners. They are calculated independently from mouse interface. I wonder if calculations are correct for scaling gnome.

**Comment by j0hannes** [comment]
I stopped using Gnome.
