### ISSUE TITLE
gnome-terminal has gap when tiling

### ISSUE THREAD

**Issue by matter123** [vibou/vibou.gTile#45]
When using gTile to position a gnome-terminal there is a gap between the edges of the tile and the edge of the window. This does not happen when tiling other programs.
![example](https://cloud.githubusercontent.com/assets/714007/15635223/936ce4c6-258d-11e6-8a62-afc096b06da7.png)
running gnome 3.18 on gentoo

**Comment by lundal** [comment]
This is a restriction in many terminal windows: The width and height must be multiples of whole characters. You can easily check if this is what's happening by manually trying to resize the window to that size.

I also had this issue before, but now (3.20) gnome-terminal can be any size and simply fills the not-quite-enough-for-a-whole-character-space with background color.

**Comment by matter123** [comment]
I do not think that is the issue because when using gnome's snap to edge it fills in the extra space.
![screenshot from 2016-05-29 11-29-00](https://cloud.githubusercontent.com/assets/714007/15635329/9c6aa236-2590-11e6-93be-14eafcfd9db5.png)

**Comment by lundal** [comment]
Perhaps by chance half of your screen is a multiple of the character width? If you use your mouse to resize the window, does the size change smoothly or jump in ~8px intervals?

For me it changes smoothly and leaves an unused edge if there is not enough space for another character. Do you see the same?
![screenshot from 2016-05-29 20-35-33](https://cloud.githubusercontent.com/assets/1502260/15635397/dd179c92-25dd-11e6-8bd1-d382b5fbd5a0.png)

**Comment by matter123** [comment]
The area of concern in the picture was the bottom of the terminals, where the gTile positioned window(on the left) has a gap but the gnome snap to edge terminal(on the right) does not. However if gnome 3.20 fixes this, I'm happy, I was planning on upgrading soon anyway.

**Comment by lundal** [comment]
Ah. I didn't know if that was your entire monitor or not.

I can tile them without edges between the windows in 3.20 at least. If you can't then we can look more into it then.
![screenshot from 2016-05-29 20-59-45](https://cloud.githubusercontent.com/assets/1502260/15635534/dd190548-25e0-11e6-9991-4336cc4e0235.png)
