### ISSUE TITLE
Default 'Super+Space' keyboard shortcut interferes with ibus

### ISSUE THREAD

**Issue by jbicha** [vibou/vibou.gTile#52]
Ubuntu GNOME 16.10

The Super+Space keyboard shortcut is already taken by ibus (and has been since ~2013) so it does not work. Please choose a different default keyboard shortcut.

**Comment by JMurph2015** [comment]
I have a fork that defaults to <Alt><Control>g, but I don't know if that is really going to be a sell-able change to existing users (for which <Super>Space works just fine at least).

**Comment by bugthing** [comment]
On my setup Super + Space changes the keyboard layout by default.. now I have installed this extension that does not work .. it would be great have it set to something different.  
Super + g as suggest by JMurph2015 works for me.

**Comment by JMurph2015** [comment]
Hi! So does the new version default to something other than Super+Space?  If not this issue really should stick around (despite now supporting Gnome 3.24, yay!).
