### ISSUE TITLE
keyboard controls

### ISSUE THREAD

**Issue by alt0xFF** [vibou/vibou.gTile#56]
The keyboard controls implemented in the Cinnamon fork is very useful:
https://github.com/shuairan/gTile
Seems like this is not available in the original (vibou.gTile)original.  Would humbly beseech you to implement this :-)

**Comment by scherepanov** [comment]
Yes, it is there... Try gTile form my repo, let me know how it looks.

**Comment by pycy** [comment]
Stupid question:  it seems that all keystrokes go to the underlying window rather than to gTile.  I can only use the mouse (and shortcut key to bring it up and dismiss the window), no other key strokes seem to do anything.

This new version is much more responsive in any case, so thank you.

**Comment by scherepanov** [comment]
Keyboard controls should work.
Super-keypad enter brings up gtile window.
When gtile window is open, try arrows and shifts arrows  (may be alt arrows do not remember)
Enter will set window.
Preset also should work.
I defined several, try super-alt-f [1-9]. Presets will work without gtile window if global presets are enabled.
You can check and redefine global presets in preferences
Let me know how it works

**Comment by pycy** [comment]
yeah still doesn't work but i am sure it's something i broke on my gnome installation.  I'll play with it more when i have some time.  appreciate!
