### ISSUE TITLE
hotkeys for specific tile position

### ISSUE THREAD

**Issue by jeremybundgaard** [vibou/vibou.gTile#59]
how can I set hotkey's to accomplish the following:

super+alt+right: tiling active window to the right 2/3 of the screen
super+alt+left  : tiling active window to the left   2/3 of the screen

super+ctlr+right: tiling active window to the right 1/3 of the screen
super+ctlr+left: tiling active window to the left 1/3 of the screen

which would be dope ;)

**Comment by scherepanov** [comment]
That was actually a good idea. Try gTile from my repo, it is implemented there, and let me know if it works for you.
I found that I am using configurable keyboard presets all the time. Very handy.

**Comment by jeremybundgaard** [comment]
Hey! thanks for your reply...
So how exactly can I use this functionality? Please provide snippets/screenshots! Thanks

**Comment by scherepanov** [comment]
New functionality is on my branch. It is not merged. Means you need to install manually from branch...
Then you will see help.

**Comment by jeremybundgaard** [comment]
I’ve checked out your branch…still not working. Please advise me

**Comment by scherepanov** [comment]
For example, out of a box Alt-Super-1 should position your window in left down quarter of a screen
You can see more predefined hotkeys in preferences, and modify them according to help.
