### ISSUE TITLE
Bottom panel height ignored

### ISSUE THREAD

**Issue by yryo617** [vibou/vibou.gTile#60]
When bottom panel is visible (often showing the notification and tabs showing all the windows open) the height of the bottom panel is never considered.
In some cases (firefox, terminal emulator) it sticks underneath the bottom panel having to manually adjust.
I would suggest that there should be an option for user to adjust or automatically take that into consideration.

**Comment by scherepanov** [comment]
This bug do exist - bottom panel height is being ignored.
To reproduce (my environment is CentOS 7.2, Gnome 3.14):
Install Gnome shell extension "Window List"
You will see that bottom panel is being ignored when placing windows.

**Comment by lundal** [comment]
At the moment, this can be worked around by setting a bottom inset.

1. Open extension.js (normally in ~/.local/share/gnome-shell/extensions/gTile@vibou)
2. Go to line 125 (the one for primary monitor insets)
3. Set bottom to the panel height (in pixels)

**Comment by scherepanov** [comment]
Yes, I look on code... I made change to account for bottom panel in settings... then I found a bug when you have second row of monitors (yes I do have a wall of monitors)... then I added full keyboard control... then I added keboard presets... then made grid selection configurable... then I added to prefecrences dialog all settings...
In short, I am waiting for Ubuntu 17.04 to be released in a week, so I can add support for 3.24, and will submit you a pull request.

**Comment by scherepanov** [comment]
Yes, it is there... code commited to repo, pull request created.
You can check if it solves your problem with bottom panal, by getting code from my repo.
