### ISSUE TITLE
Make compatible with panel extensions

### ISSUE THREAD

**Issue by amankhoza** [vibou/vibou.gTile#62]
This seems like a great plugin, any chance you could make it compatible with plugins that manipulate the position of the panel, such as dash-to-panel:

https://extensions.gnome.org/extension/1160/dash-to-panel/

**Comment by lundal** [comment]
At the moment, this can be worked around by setting a bottom inset.

1. Open extension.js (normally in ~/.local/share/gnome-shell/extensions/gTile@vibou)
2. Go to line 125 (the one for primary monitor insets)
3. Set bottom to the dock height (in pixels)

**Comment by amankhoza** [comment]
Great thanks for the tip, I didn't think to start tweaking the code. I have got it working by modifying the getWorkArea function on line 586. I changed:

**Comment by scherepanov** [comment]
I addressed this problem in more generic way. Please try gTile from my repo and tell me if it works for you.

**Comment by amankhoza** [comment]
@scherepanov Yep just tried it, it works.

**Comment by scherepanov** [comment]
Out of curiosity, what version of Gnome shell?
I stuck with 3.14, as I am using CentOS 7.2.

**Comment by amankhoza** [comment]
I'm running Fedora 24 with GNOME 3.20.4.
