### ISSUE TITLE
Dual monitor problem (on second monitor there is always empty space on top of the screen)

### ISSUE THREAD

**Issue by ge0rgecz** [vibou/vibou.gTile#63]
Dual monitor problem.
On second monitor there is no visible top bar, but this space always stays empty. Screenshot attached https://goo.gl/9r8o6c

**Comment by scherepanov** [comment]
My bet second monitor is on top of primary monitor. I saw related bug.
Try gTile from my repo, it is fixed there, and let me know if fix works for you.
